In [37]:
import numpy as np
from numpy import genfromtxt 
#generates an array from a text file

In [38]:
data = genfromtxt("../../DATA/bank_note_data.txt", delimiter=",")

In [39]:
data

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699,   0.     ],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ,   0.     ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645,   0.     ],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ,   1.     ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ,   1.     ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ,   1.     ]])

In [40]:
labels = data[:,4]

In [41]:
labels

array([0., 0., 0., ..., 1., 1., 1.])

In [42]:
features = data[:,0:4]

In [43]:
features

array([[  3.6216 ,   8.6661 ,  -2.8073 ,  -0.44699],
       [  4.5459 ,   8.1674 ,  -2.4586 ,  -1.4621 ],
       [  3.866  ,  -2.6383 ,   1.9242 ,   0.10645],
       ...,
       [ -3.7503 , -13.4586 ,  17.5932 ,  -2.7771 ],
       [ -3.5637 ,  -8.3827 ,  12.393  ,  -1.2823 ],
       [ -2.5419 ,  -0.65804,   2.6842 ,   1.1952 ]])

In [44]:
X = features
y = labels

In [45]:
# Split the data into a training and test set with the Psychic Learn library
from sklearn.model_selection import train_test_split

In [46]:
# 33% of data is going to go to the test set X_test
# 33% of labels y_test
# 42% od data is going to be shuffleld before we actually split it into a training set and a test set
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.33, random_state=42)

In [47]:
# 100% of data
len(X)

1372

In [48]:
# 60% of my data for the features is now an X_train
len(X_train)

919

In [49]:
# 33% of it is now an X_test
len(X_test)

453

In [50]:
X_test.max()

17.1116

In [51]:
X_test.min()

-13.2869

In [52]:
# Standarize or scale data
from sklearn.preprocessing import MinMaxScaler

In [53]:
# We are going to force all the features data to fall within a certain range
# this can halp the neural network actually perform better for this small data set

In [54]:
scalar_object = MinMaxScaler()

In [55]:
scalar_object.fit(X_train)

MinMaxScaler(copy=True, feature_range=(0, 1))

In [56]:
scaled_X_train = scalar_object.transform(X_train)

In [57]:
scaled_X_test = scalar_object.transform(X_test)

In [58]:
scaled_X_train.max()

1.0000000000000002

In [59]:
from keras.models import Sequential
from keras.layers import Dense

In [60]:
model = Sequential()

model.add(Dense(4,input_dim=4,activation='relu'))

# Densely connected layer. A layer right in the middle of the neural network.
model.add(Dense(8,activation='relu'))

# output layer
model.add(Dense(1,activation='sigmoid'))

In [61]:
model.compile(loss='binary_crossentropy', optimizer='adam',metrics=['accuracy'])

In [62]:
model.fit(scaled_X_train,y_train,epochs=50,verbose=2)

Epoch 1/50
 - 0s - loss: 0.6653 - acc: 0.7073
Epoch 2/50
 - 0s - loss: 0.6523 - acc: 0.6594
Epoch 3/50
 - 0s - loss: 0.6397 - acc: 0.6746
Epoch 4/50
 - 0s - loss: 0.6274 - acc: 0.6605
Epoch 5/50
 - 0s - loss: 0.6100 - acc: 0.7095
Epoch 6/50
 - 0s - loss: 0.5866 - acc: 0.7595
Epoch 7/50
 - 0s - loss: 0.5678 - acc: 0.7802
Epoch 8/50
 - 0s - loss: 0.5489 - acc: 0.7878
Epoch 9/50
 - 0s - loss: 0.5305 - acc: 0.8107
Epoch 10/50
 - 0s - loss: 0.5128 - acc: 0.8237
Epoch 11/50
 - 0s - loss: 0.4961 - acc: 0.8172
Epoch 12/50
 - 0s - loss: 0.4784 - acc: 0.8313
Epoch 13/50
 - 0s - loss: 0.4622 - acc: 0.8335
Epoch 14/50
 - 0s - loss: 0.4468 - acc: 0.8357
Epoch 15/50
 - 0s - loss: 0.4331 - acc: 0.8466
Epoch 16/50
 - 0s - loss: 0.4200 - acc: 0.8444
Epoch 17/50
 - 0s - loss: 0.4079 - acc: 0.8542
Epoch 18/50
 - 0s - loss: 0.3963 - acc: 0.8575
Epoch 19/50
 - 0s - loss: 0.3864 - acc: 0.8607
Epoch 20/50
 - 0s - loss: 0.3759 - acc: 0.8585
Epoch 21/50
 - 0s - loss: 0.3665 - acc: 0.8640
Epoch 22/50
 - 0s - lo

In [76]:
# PREDICTIONS
#model.predict_classes(scaled_X_test)

In [75]:
# EVALUATE OUR MODEL
model.metrics_names

['loss', 'acc']

In [67]:
from sklearn.metrics import confusion_matrix,classification_report

In [68]:
predictions = model.predict_classes(scaled_X_test)

In [69]:
confusion_matrix(y_test,predictions)

array([[252,   5],
       [ 23, 173]], dtype=int64)

In [70]:
print(classification_report(y_test,predictions))

             precision    recall  f1-score   support

        0.0       0.92      0.98      0.95       257
        1.0       0.97      0.88      0.93       196

avg / total       0.94      0.94      0.94       453



In [71]:
model.save('mysupermodel.h5')

In [72]:
from keras.models import load_model

In [73]:
newmodel = load_model('mysupermodel.h5')

In [77]:
newmodel.predict_classes(scaled_X_test)

array([[0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [0],
       [1],
       [1],
       [0],
       [1],
       [1],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [1],
       [0],
       [0],
       [1],
       [1],
       [1],
       [1],
       [0],
       [0],
    